version: '2'
services:
  web:
    image: ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
    networks:
      mynet:
        aliases:
          - 'm0pll.co.uk'
          - 'www.m0pll.co.uk'
          - 'ip.plett.net'
          - 'ipv4.plett.net'
          - 'ipv6.plett.net'
          - 'bold-silence-8386.fly.dev'
    environment:
      - FLY_REGION=none
  tests:
    build: tests
    depends_on:
      - web
    networks:
      - mynet

networks:
  mynet:


