version: '2'
services:
  web:
    build: .
    networks:
      mynet:
        aliases:
          - 'm0pll.co.uk'
          - 'www.m0pll.co.uk'
          - 'ip.plett.net'
    environment:
      - FLY_REGION=none
  tests:
    build: tests
    depends_on:
      - web
    networks:
      - mynet

networks:
  mynet:


